#!/bin/bash
set -ex
if [ $# -eq 1 ]; then
	usb=$1
else
	# get usb that is not mounted as rootfs
	usb=$(ls /dev/sd* | grep 'sd[a-z]$' | grep -v $(lsblk | grep -P 'sd[a-z].*\s\/$' | grep -o 'sd[a-z]'))
fi
sudo parted -s $usb mklabel gpt
sudo dd if=$(find build-artifacts -name "ubuntu-core*.img" | head -1) of=$usb bs=32M status=progress conv=fsync; sync

